#!/usr/bin/env bash
set -euo pipefail

if ! command -v pacman >/dev/null 2>&1; then
	echo "This script requires pacman (Arch/Arch-based distro)." >&2
	exit 1
fi

if [[ "${1:-}" == "--noconfirm" ]]; then
	pacman_flags=(--needed --noconfirm)
else
	pacman_flags=(--needed)
fi

packages=(
	# Base
	base
	linux-zen
	linux-firmware
	sof-firmware
	linux-zen-headers
	networkmanager
	grub
	pipewire
	sudo
	cryptsetup
	lvm2
	efibootmgr

	# Disk
	btrfs-progs
	snapper

	# Terminal
	zsh
	kitty
	eza

	# Programming
	base-devel
	cmake
	ninja
	clang
	rust
	go
	zig
	nim
	python
	ghc
	php
	texlive
	julia
	nginx
	nasm

	# Apps
	firefox
	neovim
	emacs
	zathura
	discord
	steam
	thunderbird
	kicad
	freecad
	openscad
	qbittorrent
	audacity
	gimp
	blender
	flatpak
	thunar
	obs-studio
	kdeconnect

	# Tools
	git
	stow
	opencode
	sagemath
	fastfetch
	btop
	yt-dlp
	vlc
	mpv
	docker
	ripgrep
	fd
	wget
	bat
	ffmpeg
	qemu-full
	fzf
	zoxide
	yazi
	tmux
	aria2
	jq
	perl-rename
	lftp
	grim
	slurp
	tcc
	tor
	trash-cli

	# Desktop
	hyprland
	hyprpaper
	hyprlock
	hyprpicker
	quickshell
	rofi
	dunst
	ly
	wl-clipboard
	cliphist

	# Backup Desktop
	bspwm
	sxhkd 
	polybar
	feh
	xorg

	# Drivers
	bluez
	cups
	nvidia-open-dkms
	nvidia-utils
	lib32-nvidia-utils
	nvidia-settings
	opencl-nvidia
	cuda

	# Fonts
	adobe-source-code-pro-fonts
	adobe-source-sans-fonts
	adobe-source-serif-fonts
	ttf-0xproto-nerd
	ttf-3270-nerd
	ttf-agave-nerd
	ttf-anonymouspro-nerd
	ttf-arimo-nerd
	ttf-bigblueterminal-nerd
	ttf-bitstream-vera-mono-nerd
	ttf-cascadia-code
	ttf-cascadia-code-nerd
	ttf-cascadia-mono-nerd
	ttf-cousine-nerd
	ttf-croscore
	ttf-d2coding-nerd
	ttf-daddytime-mono-nerd
	ttf-dejavu
	ttf-dejavu-nerd
	ttf-droid
	ttf-envycoder-nerd
	ttf-fantasque-nerd
	ttf-fira-code
	ttf-firacode-nerd
	ttf-go-nerd
	ttf-gohu-nerd
	ttf-hack
	ttf-hack-nerd
	ttf-heavydata-nerd
	ttf-iawriter-nerd
	ttf-ibmplex-mono-nerd
	ttf-inconsolata
	ttf-inconsolata-go-nerd
	ttf-inconsolata-lgc-nerd
	ttf-inconsolata-nerd
	ttf-intone-nerd
	ttf-iosevka-nerd
	ttf-iosevkaterm-nerd
	ttf-iosevkatermslab-nerd
	ttf-jetbrains-mono-nerd
	ttf-junicode
	ttf-lekton-nerd
	ttf-liberation
	ttf-liberation-mono-nerd
	ttf-lilex-nerd
	ttf-martian-mono-nerd
	ttf-meslo-nerd
	ttf-monofur-nerd
	ttf-monoid-nerd
	ttf-mononoki-nerd
	ttf-mplus-nerd
	# ttf-nanumgothic_coding
	ttf-nerd-fonts-symbols
	ttf-nerd-fonts-symbols-mono
	ttf-noto-nerd
	ttf-profont-nerd
	ttf-proggyclean-nerd
	ttf-recursive-nerd
	ttf-roboto-mono-nerd
	ttf-sharetech-mono-nerd
	ttf-sourcecodepro-nerd
	ttf-space-mono-nerd
	ttf-terminus-nerd
	ttf-tinos-nerd
	ttf-ubuntu-font-family
	ttf-ubuntu-mono-nerd
	ttf-ubuntu-nerd
	ttf-victor-mono-nerd
	ttf-zed-mono-nerd

	# Music
	reaper
	timidity++
	mpd
	mpc
	rmpc
)

sudo pacman -S "${pacman_flags[@]}" "${packages[@]}"
