#!/bin/sh
# ██████╗░██╗░░██╗░░░░░░██████╗░░██████╗██████╗░░██╗░░░░░░░██╗███╗░░░███╗ #
# ██╔══██╗██║░░██║░░░░░░██╔══██╗██╔════╝██╔══██╗░██║░░██╗░░██║████╗░████║ #
# ██████╦╝███████║█████╗██████╦╝╚█████╗░██████╔╝░╚██╗████╗██╔╝██╔████╔██║ #
# ██╔══██╗██╔══██║╚════╝██╔══██╗░╚═══██╗██╔═══╝░░░████╔═████║░██║╚██╔╝██║ #
# ██████╦╝██║░░██║░░░░░░██████╦╝██████╔╝██║░░░░░░░╚██╔╝░╚██╔╝░██║░╚═╝░██║ #
# ╚═════╝░╚═╝░░╚═╝░░░░░░╚═════╝░╚═════╝░╚═╝░░░░░░░░╚═╝░░░╚═╝░░╚═╝░░░░░╚═╝ #
# 
# █▄▄ █░█ ▀ █▀   █▀▀ █▀█ █▄░█ █▀▀ █ █▀▀   █▀▀ █▀█ █▀█   █▄▄ █▀ █▀█ █░█░█ █▀▄▀█ #
# █▄█ █▀█ ░ ▄█   █▄▄ █▄█ █░▀█ █▀░ █ █▄█   █▀░ █▄█ █▀▄   █▄█ ▄█ █▀▀ ▀▄▀▄▀ █░▀░█ #


# Colours

darkcyan="#007575"
lightcyan="#1ebaba"
lightercyan="#19e0e0"
red="#e55235"


# Keybindings

# /home/bh/.config/bspwm/scripts/keyboard & # Capslock to Backspace
# setxkbmap -layout "us,us,cn,jp,ru" -variant "dvorak,,wubi,,," -option "grp:ctrl_shift_toggle"

pgrep -x sxhkd > /dev/null || sxhkd -c /home/bh/.config/sxhkd/sxhkdrc & # Checks if sxhkd is running. If not, it is started.

# Workspaces

# bspc monitor -d 1 2 3 4 5 6 7 8 9 10
# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 壹 貳 參 肆 伍 陸 柒 捌 玖 拾
bspc monitor -d 一 二 三 四 五 六 七 八 九 十 󱉼

# Windows
bspc config border_width	1
bspc config window_gap  	6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "$lightercyan"
bspc config normal_border_color "$darkcyan"
bspc config urgent_border_color "$red" 
bspc config presel_feedback_color "$lightercyan"


# Startup

kitty & # Opens Two
kitty & # Terminal Emulators

polybar & # Opens Status Bar

# feh --bg-fill /home/bh/Pictures/Wallpapers/NightMountain.jpg & # Wallpaper
# feh --bg-fill /home/bh/Pictures/Wallpapers/BlueMountain.jpg & # Wallpaper
# feh --bg-fill /home/bh/Pictures/Wallpapers/CloudyBluishMountain.jpg & # Wallpaper
# feh --bg-fill /home/bh/Pictures/Wallpapers/TealNebula.jpg & # Wallpaper
feh --bg-fill /home/bh/Dotfiles/.assets/Wallpapers/TealNebula.jpg & # Wallpaper



# Application Rules

# bspc rule -a "kitty" desktop=^1 follow=on # Only Opens Kitty in Desktop 1
bspc rule -a "firefox" desktop=^2 follow=on # Only Opens Firefox in Desktop 2
# bspc rule -a "zen" desktop=^2 follow=on # Only Opens Zen-Browser in Desktop 2
bspc rule -a "Emacs" desktop=^3 follow=on # Only Opens Emacs in Desktop 3


# Floating Class
bspc rule -a floating state=floating

# Compositor
# picom --config  ~/.config/picom/picom.conf & # Compositor

# Notifications
dunst &
