;==========================================================
;
;
;   ██████╗░██╗░░██╗░░░░░░██████╗░░█████╗░██████╗░
;   ██╔══██╗██║░░██║░░░░░░██╔══██╗██╔══██╗██╔══██╗
;   ██████╦╝███████║█████╗██████╦╝███████║██████╔╝
;   ██╔══██╗██╔══██║╚════╝██╔══██╗██╔══██║██╔══██╗
;   ██████╦╝██║░░██║░░░░░░██████╦╝██║░░██║██║░░██║
;   ╚═════╝░╚═╝░░╚═╝░░░░░░╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
; background = #BF003636
; background-alt = #CC0d6063

; High Transparency
; background = #33003636
; background = #00003636
; background = #8C003636

#background = #A6003636
background = #003636
background-alt = #CC0d6063
transparent = #00000000

# background-2 = #004344
background-2 = #004344


foreground = #C5C8C6
primary = #6ae8eb
secondary = #8ABEB7
alert = #A54242
# darkerteal = #015959
fade = #015959

active = #8affff
# disabled = #707880
disabled = #4d7f7f
selected = #ffc600

[bar/primary]
width = 100%
height = 25

font-0 = "Source Code Pro:size=10.5:style=Normal"
# font-0 = xft:DejaVu Sans:size=11:style=Normal
# font-1 = "JetBrains Mono:size=12;1"
font-1 = "Symbols Nerd Font:style=Regular:size=9;1"
font-2 = Noto Sans CJK SC;1
font-3 = "Inconsolata for Powerline:pixelsize=18.75:antialias=true;3"

radius = 0

# background = ${colors.background}
background = ${colors.transparent}
foreground = ${colors.primary}

line-size = 3pt

# border-size = 1pt
# border-color = ${colors.transparent}
# border-color = ${colors.background}

padding-left = 0
padding-right = 0

module-margin = 0

# separator = " | "
# separator = "  "
# separator-foreground = ${colors.fade}

modules-left = wlan sep-right xwindow sep-right-last
modules-center = xworkspaces
modules-right = sep-left-last filesystem sep-left-2 pulseaudio sep-left xkeyboard sep-left-2 memory sep-left cpu sep-left-2 date sep-left time 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = bspwm

#[module/systray]
#type = internal/tray
#
#format-margin = 8pt
#tray-spacing = 16pt

[module/xwindow]
type = internal/xwindow

format-prefix = " "
format-prefix-foreground = ${colors.primary}

format-background  = ${colors.background-2}
format-padding  = 1
label-maxlen = 50

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
# label-active-background = ${colors.background}
# label-active-foreground = ${colors.primary}
label-active-foreground = ${colors.selected}
label-active-padding = 1.5

label-occupied = %name%
label-occupied-foreground = ${colors.active}
label-occupied-padding = 1.5

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1.5

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1.5

[module/xkeyboard]
type = internal/xkeyboard

format-prefix = "󰌌 "
format-prefix-foreground = ${colors.primary}

blacklist-0 = num lock
label-layout = %layout%

format-background  = ${colors.background}
format-padding  = 1


[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/filesystem]
type = internal/fs

format-mounted-background  = ${colors.background}
format-unmounted-background  = ${colors.background}
format-padding  = 1

interval = 25

mount-0 = /

label-mounted =  %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}


[module/pulseaudio]
type = internal/pulseaudio

# format-volume-prefix = "VOL "
# format-volume-prefix-foreground = ${colors.primary}
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

format-volume-background  = ${colors.background-2}
format-muted-background  = ${colors.background-2}
format-volume-padding  = 1
format-muted-padding  = 1


[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

format-background  = ${colors.background-2}
format-padding  = 1

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = ""
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

format-background  = ${colors.background}
format-padding  = 1


[module/wlan]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = 󱚼 %{F#F0C674}%ifname%%{F#707880} disconnected
interface-type = wireless
label-connected =  %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

format-connected-background  = ${colors.background}
format-disconnected-background  = ${colors.background}
format-connected-padding  = 1
format-disconnected-padding  = 1

[module/date]
type = custom/script
format-prefix = " "
exec = ~/.config/polybar/date
interval = 1

format-background  = ${colors.background-2}
format-padding  = 1

[module/time]
type = internal/date

format-prefix = "󰥔 "
format-prefix-foreground = ${colors.primary}

interval = 0.00001
date = %H:%M:%S

format-background  = ${colors.background}
format-padding  = 1

# Powerline Separators
[module/sep-left]
type = custom/text
label-foreground  = ${colors.background}
format-background  = ${colors.background-2}
label = "%{T4}%{T-}"

[module/sep-left-2]
type = custom/text
label-foreground  = ${colors.background-2}
format-background  = ${colors.background}
label = "%{T4}%{T-}"

[module/sep-left-last]
type = custom/text
label-foreground  = ${colors.background}
format-background  = ${colors.transparent}
label = "%{T4}%{T-}"

[module/sep-right]
type = custom/text
label-foreground  = ${colors.background}
format-background  = ${colors.background-2}
label = "%{T4}%{T-}"

[module/sep-right-2]
type = custom/text
label-foreground  = ${colors.background-2}
format-background  = ${colors.background}
label = "%{T4}%{T-}"

[module/sep-right-last]
type = custom/text
label-foreground  = ${colors.background-2}
format-background  = ${colors.transparent}
label = "%{T4}%{T-}"


[settings]
pseudo-transparency = true
