# TMUX Keybinding
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Turn status bar on
set -g status on

# Background + foreground color
set -ga terminal-overrides ",xterm-256color:RGB"

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# Status bar colors
set -g status-bg "#003636"
set -g status-fg "#004344"
# set -g status-fg "#225859"

# Window status - inactive windows with powerline separators
set -g window-status-format "#[fg=#015959,bg=#003636]#[fg=#FFFFFF,bg=#015959]#I #[fg=#6ae8eb,bg=#004344] #W #[fg=#004344,bg=#003636]"
set -g window-status-current-format "#[fg=#008282,bg=#003636]#[fg=#FFFFFF,bg=#008282]#I #[fg=#6ae8eb,bg=#004344] #W #[fg=#004344, bg=#003636]"

# Previous Settings
# set -g window-status-format "#[fg=#004344,bg=#003636]#[fg=#6ae8eb,bg=#004344]#I|#W #[fg=#004344,bg=#003636]"
# set -g window-status-current-format "#[fg=#008282,bg=#003636]#[fg=#FFFFFF,bg=#008282]#I|#W #[fg=#008282, bg=#003636]"

# set -g window-status-format "#[fg=#74c4c4,bg=#004344] #I|#W #[fg=#004344,bg=#003636] "

# set -g window-status-format "#[fg=#002a2b,bg=#003636]#[fg=#74c4c4,bg=#002a2b] #I|#W #[fg=#002a2b,bg=#003636]"
# set -g window-status-current-format "#[fg=#008282,bg=#003636]#[fg=#FFFFFF,bg=#008282] #I|#W #[fg=#008282,bg=#003636]"

# Status bar configuration - disabled all modules except windows
set -g status-left-length 1000
set -g status-right-length 1000
set -g status-left "#[fg=#74c4c4]#S "
set -g status-right "#[fg=#004344, bg=#003636]#[fg=#6ae8eb,bg=#004344] %H:%M #[fg=#FFFFFF,bg=#008282]  #[fg=#008282,bg=#003636]"

# Pane border colors
set -g pane-border-style "fg=#007575"
set -g pane-active-border-style "fg=#1FDFDF"

# Keybindings
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -n M-h resize-pane -L 2
bind -n M-j resize-pane -D 2
bind -n M-k resize-pane -U 2
bind -n M-l resize-pane -R 2

bind-key Tab last-window

# # List of plugins
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# 
# # Initialize TMUX plugin manager (keep this line at the very bottom)
# run '~/.tmux/plugins/tpm/tpm'
