# ██████╗░██╗░░██╗░░░░░░██╗░░██╗██╗████████╗████████╗██╗░░░██╗
# ██╔══██╗██║░░██║░░░░░░██║░██╔╝██║╚══██╔══╝╚══██╔══╝╚██╗░██╔╝
# ██████╦╝███████║█████╗█████═╝░██║░░░██║░░░░░░██║░░░░╚████╔╝░
# ██╔══██╗██╔══██║╚════╝██╔═██╗░██║░░░██║░░░░░░██║░░░░░╚██╔╝░░
# ██████╦╝██║░░██║░░░░░░██║░╚██╗██║░░░██║░░░░░░██║░░░░░░██║░░░
# ╚═════╝░╚═╝░░╚═╝░░░░░░╚═╝░░╚═╝╚═╝░░░╚═╝░░░░░░╚═╝░░░░░░╚═╝░░░


# Theme
include theme.conf

# Font

# font_family      Source Code Pro
# font_family      FiraCode Nerd Font
# font_family      Fira Code
# font_family      JetBrains Mono
# font_family      JetBrains Mono Nerd
# font_family      Consolas
# font_family      Cascadia Code
# font_family Inconsolata
# font_family Hack
font_family      JetBrainsMono Nerd Font

bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 10.5

# Terminal
# background_opacity 0.60
background_opacity 0.75
# background_opacity 0.00
background_blur 1

window_padding_width 5

# Scrolling
scrollback_lines 10000

# Allows Remote Control
allow_remote_control yes

# Tabs

tab_bar_style powerline

# Bell
visual_bell_duration 0.1
# bell_path ~/.config/kitty/bell.ogg
bell_path ~/.config/kitty/hihat.ogg

# No Ligatures
# disable_ligatures always
# font_features none

# Disable Cursor Shape Change in Shell
shell_integration no-cursor

# Copy-Paste
copy_on_select clipboard

# No Cursor Blinking
cursor_blink_interval 0

# Trail
cursor_trail 1
cursor_trail_start_threshold 0
