# The basic colors
foreground              #8affff
background              #003636
selection_foreground    #FFFFFF
selection_background    #395e5e

# Cursor colors
cursor                  #FFC600
cursor_text_color       #1C1C1C

# URL underline color when hovering with mouse
url_color               #8affff

# Kitty window border colors
active_border_color     #8affff
inactive_border_color   #477576
bell_border_color       #F2ED7F

# Tab bar colors
active_tab_foreground   #FFFFFF
active_tab_background #008181
inactive_tab_background   #065959
inactive_tab_foreground #FFFFFF

# Colors for marks (marked text in the terminal)
mark1_foreground #FFC600
mark1_background #3AD900
mark2_foreground #967EFB
mark2_background #00AAFF
mark3_foreground #FF628C
mark3_background #FF9A00

# The 16 terminal colors

# black
color0 #1C1C1C
color8 #9E9E9E

# red
color1 #ff373d
color9 #ca000b

# green
color2  #1fff66
color10 #70ff00

# yellow
color3  #FFC600
color11 #FF9A00

# cyan
color6  #80FCFF
color14 #8fbfdc

# magenta
color5  #FF628C
color13 #ff00da

# blue
color4  #0080FF
color12 #0056ac

# white
color7  #FFFFFF
color15 #BCBCBC
